/**
 * 自动生成:
   * - 100 男性
 * - 100 女性
 * - 50 动物
 * - 50 风景
  * 
  * - 生成时间: 2026/8/9 18:30:06
  */

  const MALE_AVATARS = [
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_10163504.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_10898851.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_10921414.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_11591182.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_13357874.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_14194707.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_14672172.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_15995470.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_15995471.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_16346814.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_16367799.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_16367802.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_16367803.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_16367811.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_16367812.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_16367815.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_16625473.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_17659438.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_19062481.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_1972716.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_21852438.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_25587930.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_26524787.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_26765343.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_28945168.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_28945175.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_29446575.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_29446599.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_29512035.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_29643325.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_29643326.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_29643327.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_30109580.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_30208891.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_30221356.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_30423787.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_30736630.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_31249010.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_31986955.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_32292167.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_32472476.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_32763795.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_32930522.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_32930602.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_32930605.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_32930606.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33342190.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33342194.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33587261.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33587273.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33587274.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33609305.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33609306.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33609311.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33609314.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33625602.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_33674755.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_34523437.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_34818719.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_34818724.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_34970889.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_34972694.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_35988655.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36010836.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36442459.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36782402.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36782459.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36782470.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36847272.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36995696.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36995699.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36995702.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_36995705.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_37169664.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_37170117.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_37288380.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_37436370.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_38721393.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_38732535.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_38765088.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_38837209.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_6214225.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_6214227.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_6214230.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_6214231.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_6214232.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_6214234.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_6214235.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_7164258.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_7164263.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_7164280.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_7164282.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_7164286.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_7164290.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_7164517.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_7242326.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_8263886.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_8794855.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_8794861.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/male/male_9471418.jpg'
];
const FEMALE_AVATARS = [
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_10343081.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_11831678.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_12972414.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_12983149.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_13011921.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_14580076.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_14894114.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_16022133.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_16514249.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_16974605.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_17784385.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_18393845.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_18820902.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_19227772.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_19227773.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_19227774.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_20265222.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_20265224.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_20318265.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_20658692.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_25070262.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_25070265.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_25070355.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_25070365.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_25070377.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_25880909.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_26645092.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_27452319.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_28479115.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_28942519.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_28942520.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_29549226.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_30738283.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_30738285.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_30851222.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_31129921.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_31129926.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_31129928.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_32209709.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_32334764.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_33866503.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_33996458.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_34234059.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_34262644.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_3574802.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_36060520.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_37206877.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38686077.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38702650.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38702666.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38721368.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38721369.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38721370.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38721385.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38721390.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38721393.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38721398.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38721401.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38732461.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38732462.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38732463.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38732466.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38732476.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38732482.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38732535.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38732549.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38765088.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38765117.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38796062.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38809643.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38809649.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38837206.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38837209.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38837212.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38837221.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38837224.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38837230.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38854183.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38854189.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38854233.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38854273.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38879595.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38879616.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38879635.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38890775.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38890776.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38910133.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38920289.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38920295.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38920297.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38920305.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38920315.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_38930948.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_5253720.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_6214080.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_6214081.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_6214087.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_6426715.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_8582581.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/female/female_8582583.jpg'
];
const ANIMAL_AVATARS = [
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_12058405.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_15416242.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_15943783.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_16144420.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_16263130.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_16491808.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_16829876.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_17742002.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_17880522.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_19197572.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_20590263.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_20678181.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_20754422.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_20754423.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_23467478.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_26793957.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_28237531.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_28273136.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_28322686.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_29253902.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_29597132.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_29605214.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_3069877.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_31131485.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_31666591.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_3173618.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_32049547.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_32705786.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_33357399.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_33376861.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_33448060.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_33448061.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_33987318.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_34006896.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_35117366.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_35151697.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_35319349.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_35438603.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_35494819.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_35848699.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_36354902.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_37348521.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_37348534.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_37348535.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_37538165.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_38432183.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_4829727.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_5488833.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_8508899.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/animal/animal_8508906.jpg'
];
const SCENERY_AVATARS = [
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_12073400.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_12073485.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_12127588.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_12825149.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_13757161.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_14200443.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_15199054.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_15770293.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_16055974.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_18923424.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_19112123.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_19497733.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_19643249.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_19786669.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_21915186.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_28722195.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_28847684.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_28940316.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_28940939.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_30614555.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_31083774.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_31829081.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_32341423.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_33995997.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_34031036.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_34302652.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_34409529.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_34640803.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_34735625.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_35312439.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_36535706.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_36535710.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_36685290.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_37210538.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_37451236.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_37801184.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_37886042.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_38098088.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_38268417.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_38414824.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_38757767.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_38757768.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_38757772.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_7906037.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_8548919.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_8830606.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_9007232.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_9007456.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_9060482.jpg',
  'https://raw.githubusercontent.com/Skyler-May/avatars/main/assets/images/scenery/scenery_9968874.jpg'
];
    export default {
      async fetch(request: { url: string | URL; }) {
        const url = new URL(request.url);
        const gender = url.pathname.split('/')[1];
        if (!['male', 'female', 'animal', 'scenery'].includes(gender)) {
          return new Response('欢迎使用头像服务，请访问 /male, /female, /animal 或 /scenery', { status: 200 });
        }
        const avatars = gender === 'male' ? MALE_AVATARS :
                    gender === 'female' ? FEMALE_AVATARS :
                    gender === 'animal' ? ANIMAL_AVATARS :
                    gender === 'scenery' ? SCENERY_AVATARS : SCENERY_AVATARS;
        if (avatars.length === 0) return new Response('暂无头像', { status: 404 });
        const randomUrl = avatars[Math.floor(Math.random() * avatars.length)];
        
        // 使用 cf.image 进行图片转换（如需禁用，可删除 cf 参数）
        const imageResponse = await fetch(randomUrl, {
          cf: {
            image: {
              width: 200,
              height: 200,
              fit: "contain",
              quality: 80
            }
          }
        } as any);
        
        const image = await imageResponse.arrayBuffer();
        const ext = randomUrl.split('.').pop()?.toLowerCase() || '';
        let contentType = 'image/jpeg';
        if (ext === 'png') contentType = 'image/png';
        else if (ext === 'webp') contentType = 'image/webp';
        else if (ext === 'gif') contentType = 'image/gif';
        const finalContentType = imageResponse.headers.get('content-type') || contentType;

        return new Response(image, {
          headers: {
            'Content-Type': finalContentType,
            'Cache-Control': 'public, max-age=86400'
          }
        });
      }
    };
  